package classes
// Generated 26 de nov. 2020, 17:51:55 by Hibernate Tools 5.2.12.Final
import java.util.HashSet
import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.FetchType
import javax.persistence.Id
import javax.persistence.OneToMany
import javax.persistence.Table

/**
 * Comarca generated by hbm2java
 */
@Entity
@Table(name = "comarca")
class Comarca : java.io.Serializable {
	@get:Id
	@get:Column(name = "nom_c", unique = true, nullable = false, length = 50)
	var nomC: String? = null

	@get:Column(name = "provincia", length = 25)
	var provincia: String? = null

	@get:OneToMany(fetch = FetchType.LAZY, mappedBy = "comarca")
	var poblacios: Set<Poblacio>? = HashSet<Poblacio>(0)

	constructor() {}
	constructor(nomC: String?) {
		this.nomC = nomC
	}

	constructor(nomC: String?, provincia: String?, poblacios: Set<Poblacio>?) {
		this.nomC = nomC
		this.provincia = provincia
		this.poblacios = poblacios
	}
}