package classes
// Generated 26 de nov. 2020, 17:51:55 by Hibernate Tools 5.2.12.Final
import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.FetchType
import javax.persistence.Id
import javax.persistence.JoinColumn
import javax.persistence.ManyToOne
import javax.persistence.Table

/**
 * Institut generated by hbm2java
 */
@Entity
@Table(name = "institut")
class Institut : java.io.Serializable {
	@get:Id
	@get:Column(name = "codi", unique = true, nullable = false, length = 8)
	var codi: String? = null

	@get:ManyToOne(fetch = FetchType.LAZY)
	@get:JoinColumn(name = "cod_m")
	var poblacio: Poblacio? = null

	@get:Column(name = "nom", length = 60)
	var nom: String? = null

	@get:Column(name = "adreca", length = 100)
	var adreca: String? = null

	@get:Column(name = "numero", length = 5)
	var numero: String? = null

	@get:Column(name = "codpostal", precision = 5, scale = 0)
	var codpostal: Integer? = null

	constructor() {}
	constructor(codi: String?) {
		this.codi = codi
	}

	constructor(
		codi: String?,
		poblacio: Poblacio?,
		nom: String?,
		adreca: String?,
		numero: String?,
		codpostal: Integer?
	) {
		this.codi = codi
		this.poblacio = poblacio
		this.nom = nom
		this.adreca = adreca
		this.numero = numero
		this.codpostal = codpostal
	}
}