package classes
// Generated 26 de nov. 2020, 17:51:55 by Hibernate Tools 5.2.12.Final
import java.math.BigDecimal
import java.util.HashSet
import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.FetchType
import javax.persistence.Id
import javax.persistence.JoinColumn
import javax.persistence.ManyToOne
import javax.persistence.OneToMany
import javax.persistence.Table

/**
 * Poblacio generated by hbm2java
 */
@Entity
@Table(name = "poblacio")
class Poblacio : java.io.Serializable {
	@get:Id
	@get:Column(name = "cod_m", unique = true, nullable = false, precision = 5, scale = 0)
	var codM: Int = 0

	@get:ManyToOne(fetch = FetchType.LAZY)
	@get:JoinColumn(name = "nom_c")
	var comarca: Comarca? = null

	@get:Column(name = "nom", nullable = false, length = 50)
	var nom: String? = null

	@get:Column(name = "poblacio", precision = 6, scale = 0)
	var poblacio: Integer? = null

	@get:Column(name = "extensio", precision = 6)
	var extensio: BigDecimal? = null

	@get:Column(name = "altura", precision = 4, scale = 0)
	var altura: Short? = null

	@get:Column(name = "longitud", length = 50)
	var longitud: String? = null

	@get:Column(name = "latitud", length = 50)
	var latitud: String? = null

	@get:Column(name = "llengua", length = 1)
	var llengua: Character? = null

	@get:OneToMany(fetch = FetchType.LAZY, mappedBy = "poblacio")
	var instituts: Set<Institut>? = HashSet<Institut>(0)

	constructor() {}
	constructor(codM: Int, nom: String?) {
		this.codM = codM
		this.nom = nom
	}

	constructor(
		codM: Int, comarca: Comarca?, nom: String?, poblacio: Integer?, extensio: BigDecimal?, altura: Short?,
		longitud: String?, latitud: String?, llengua: Character?, instituts: Set<Institut>?
	) {
		this.codM = codM
		this.comarca = comarca
		this.nom = nom
		this.poblacio = poblacio
		this.extensio = extensio
		this.altura = altura
		this.longitud = longitud
		this.latitud = latitud
		this.llengua = llengua
		this.instituts = instituts
	}
}