package classes;
// Generated 26 de nov. 2020, 17:35:42 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Comarca generated by hbm2java
 */
@Entity
@Table(name = "comarca")
public class Comarca implements java.io.Serializable {

	private String nomC;
	private String provincia;
	private Set<Poblacio> poblacios = new HashSet<Poblacio>(0);

	public Comarca() {
	}

	public Comarca(String nomC) {
		this.nomC = nomC;
	}

	public Comarca(String nomC, String provincia, Set<Poblacio> poblacios) {
		this.nomC = nomC;
		this.provincia = provincia;
		this.poblacios = poblacios;
	}

	@Id

	@Column(name = "nom_c", unique = true, nullable = false, length = 50)
	public String getNomC() {
		return this.nomC;
	}

	public void setNomC(String nomC) {
		this.nomC = nomC;
	}

	@Column(name = "provincia", length = 25)
	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comarca")
	public Set<Poblacio> getPoblacios() {
		return this.poblacios;
	}

	public void setPoblacios(Set<Poblacio> poblacios) {
		this.poblacios = poblacios;
	}

}
