package classes;
// Generated 26 de nov. 2020, 17:35:42 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Institut generated by hbm2java
 */
@Entity
@Table(name = "institut")
public class Institut implements java.io.Serializable {

	private String codi;
	private Poblacio poblacio;
	private String nom;
	private String adreca;
	private String numero;
	private Integer codpostal;

	public Institut() {
	}

	public Institut(String codi) {
		this.codi = codi;
	}

	public Institut(String codi, Poblacio poblacio, String nom, String adreca, String numero, Integer codpostal) {
		this.codi = codi;
		this.poblacio = poblacio;
		this.nom = nom;
		this.adreca = adreca;
		this.numero = numero;
		this.codpostal = codpostal;
	}

	@Id

	@Column(name = "codi", unique = true, nullable = false, length = 8)
	public String getCodi() {
		return this.codi;
	}

	public void setCodi(String codi) {
		this.codi = codi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_m")
	public Poblacio getPoblacio() {
		return this.poblacio;
	}

	public void setPoblacio(Poblacio poblacio) {
		this.poblacio = poblacio;
	}

	@Column(name = "nom", length = 60)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "adreca", length = 100)
	public String getAdreca() {
		return this.adreca;
	}

	public void setAdreca(String adreca) {
		this.adreca = adreca;
	}

	@Column(name = "numero", length = 5)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "codpostal", precision = 5, scale = 0)
	public Integer getCodpostal() {
		return this.codpostal;
	}

	public void setCodpostal(Integer codpostal) {
		this.codpostal = codpostal;
	}

}
