package classes;
// Generated 26 de nov. 2020, 17:35:42 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Poblacio generated by hbm2java
 */
@Entity
@Table(name = "poblacio")
public class Poblacio implements java.io.Serializable {

	private int codM;
	private Comarca comarca;
	private String nom;
	private Integer poblacio;
	private BigDecimal extensio;
	private Short altura;
	private String longitud;
	private String latitud;
	private Character llengua;
	private Set<Institut> instituts = new HashSet<Institut>(0);

	public Poblacio() {
	}

	public Poblacio(int codM, String nom) {
		this.codM = codM;
		this.nom = nom;
	}

	public Poblacio(int codM, Comarca comarca, String nom, Integer poblacio, BigDecimal extensio, Short altura,
			String longitud, String latitud, Character llengua, Set<Institut> instituts) {
		this.codM = codM;
		this.comarca = comarca;
		this.nom = nom;
		this.poblacio = poblacio;
		this.extensio = extensio;
		this.altura = altura;
		this.longitud = longitud;
		this.latitud = latitud;
		this.llengua = llengua;
		this.instituts = instituts;
	}

	@Id

	@Column(name = "cod_m", unique = true, nullable = false, precision = 5, scale = 0)
	public int getCodM() {
		return this.codM;
	}

	public void setCodM(int codM) {
		this.codM = codM;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nom_c")
	public Comarca getComarca() {
		return this.comarca;
	}

	public void setComarca(Comarca comarca) {
		this.comarca = comarca;
	}

	@Column(name = "nom", nullable = false, length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "poblacio", precision = 6, scale = 0)
	public Integer getPoblacio() {
		return this.poblacio;
	}

	public void setPoblacio(Integer poblacio) {
		this.poblacio = poblacio;
	}

	@Column(name = "extensio", precision = 6)
	public BigDecimal getExtensio() {
		return this.extensio;
	}

	public void setExtensio(BigDecimal extensio) {
		this.extensio = extensio;
	}

	@Column(name = "altura", precision = 4, scale = 0)
	public Short getAltura() {
		return this.altura;
	}

	public void setAltura(Short altura) {
		this.altura = altura;
	}

	@Column(name = "longitud", length = 50)
	public String getLongitud() {
		return this.longitud;
	}

	public void setLongitud(String longitud) {
		this.longitud = longitud;
	}

	@Column(name = "latitud", length = 50)
	public String getLatitud() {
		return this.latitud;
	}

	public void setLatitud(String latitud) {
		this.latitud = latitud;
	}

	@Column(name = "llengua", length = 1)
	public Character getLlengua() {
		return this.llengua;
	}

	public void setLlengua(Character llengua) {
		this.llengua = llengua;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poblacio")
	public Set<Institut> getInstituts() {
		return this.instituts;
	}

	public void setInstituts(Set<Institut> instituts) {
		this.instituts = instituts;
	}

}
