package classes
// Generated 19 de febr. 2021, 20:23:47 by Hibernate Tools 5.2.12.Final
/**
 * PuntId generated by hbm2java
 */
class PuntId : java.io.Serializable {
	var numR: Int = 0
	var numP: Int = 0

	constructor() {}
	constructor(numR: Int, numP: Int) {
		this.numR = numR
		this.numP = numP
	}

	override fun equals(other: Any?): Boolean {
		if ((this === other))
			return true
		if ((other == null))
			return false
		if (!(other is PuntId))
			return false
		val castOther = other as PuntId?
		return (this.numR == castOther!!.numR) && (this.numP == castOther!!.numP)
	}

	override fun hashCode(): Int {
		var result = 17
		result = 37 * result + this.numR
		result = 37 * result + this.numP
		return result
	}
}