package classes
// Generated 13 de nov. 2020, 9:05:01 by Hibernate Tools 5.2.12.Final
import java.util.HashSet

/**
 * Ruta generated by hbm2java
 */
class Ruta : java.io.Serializable {
	var numR: Int = 0
	var nomR: String? = null
	var desnivell: Integer? = null
	var desnivellAcumulat: Integer? = null
	var punts: Set<Punt>? = HashSet<Punt>(0)

	constructor() {}
	constructor(numR: Int) {
		this.numR = numR
	}

	constructor(numR: Int, nomR: String?, desnivell: Integer?, desnivellAcumulat: Integer?, punts: Set<Punt>?) {
		this.numR = numR
		this.nomR = nomR
		this.desnivell = desnivell
		this.desnivellAcumulat = desnivellAcumulat
		this.punts = punts
	}
}