package classesBiblio
// Generated 20 de febr. 2021, 19:14:36 by Hibernate Tools 5.2.12.Final
import java.util.HashSet

/**
 * Autor generated by hbm2java
 */
class Autor : java.io.Serializable {
	var codA: String? = null
	var nom: String? = null
	var llibres: Set<Llibre>? = HashSet<Llibre>(0)

	constructor() {}
	constructor(codA: String?) {
		this.codA = codA
	}

	constructor(codA: String?, nom: String?, llibres: Set<Llibre>?) {
		this.codA = codA
		this.nom = nom
		this.llibres = llibres
	}
}