package classesBiblio
// Generated 20 de febr. 2021, 19:14:36 by Hibernate Tools 5.2.12.Final
import java.util.HashSet

/**
 * Llibre generated by hbm2java
 */
class Llibre : java.io.Serializable {
	var isbn: String? = null
	var editorial: Editorial? = null
	var titol: String? = null
	var pagines: Integer? = null
	var autors: Set<Autor>? = HashSet<Autor>(0)

	constructor() {}
	constructor(isbn: String?) {
		this.isbn = isbn
	}

	constructor(isbn: String?, editorial: Editorial?, titol: String?, pagines: Integer?, autors: Set<Autor>?) {
		this.isbn = isbn
		this.editorial = editorial
		this.titol = titol
		this.pagines = pagines
		this.autors = autors
	}
}