package classes
// Generated 16/03/2020 13:37:30 by Hibernate Tools 5.2.12.Final
import java.util.HashSet

/**
 * Comarca generated by hbm2java
 */
class Comarca : java.io.Serializable {
	var nomC: String? = null
	var provincia: String? = null
	var poblacios: Set<Poblacio>? = HashSet<Poblacio>(0)

	constructor() {}
	constructor(nomC: String?) {
		this.nomC = nomC
	}

	constructor(nomC: String?, provincia: String?, poblacios: Set<Poblacio>?) {
		this.nomC = nomC
		this.provincia = provincia
		this.poblacios = poblacios
	}
}