package classes
// Generated 2 de nov. 2020, 8:37:52 by Hibernate Tools 5.4.18.Final
/**
 * Usuari generated by hbm2java
 */
class Usuari : java.io.Serializable {
	var num: Int = 0
	var missatge: String? = null
	var nom: String? = null

	constructor() {}
	constructor(num: Int) {
		this.num = num
	}

	constructor(num: Int, missatge: String?, nom: String?) {
		this.num = num
		this.missatge = missatge
		this.nom = nom
	}
}