package classes
// Generated 15 de nov. 2020, 14:40:02 by Hibernate Tools 5.2.12.Final
import java.util.Date
import java.util.HashSet

/**
 * Alumne generated by hbm2java
 */
class Alumne : java.io.Serializable {
	var dni: String? = null
	var professor: Professor? = null
	var nom: String? = null
	var dataN: Date? = null
	var diaC: String? = null
	var horaC: Double? = null
	var aprovat: String? = null
	var baixa: String? = null
	var practiqueses: Set<Practiques>? = HashSet<Practiques>(0)
	var examens: Set<Examen>? = HashSet<Examen>(0)

	constructor() {}
	constructor(dni: String?) {
		this.dni = dni
	}

	constructor(
		dni: String?,
		professor: Professor?,
		nom: String?,
		dataN: Date?,
		diaC: String?,
		horaC: Double?,
		aprovat: String?,
		baixa: String?,
		practiqueses: Set<Practiques>?,
		examens: Set<Examen>?
	) {
		this.dni = dni
		this.professor = professor
		this.nom = nom
		this.dataN = dataN
		this.diaC = diaC
		this.horaC = horaC
		this.aprovat = aprovat
		this.baixa = baixa
		this.practiqueses = practiqueses
		this.examens = examens
	}
}