package classes
// Generated 15 de nov. 2020, 14:40:02 by Hibernate Tools 5.2.12.Final
/**
 * Examen generated by hbm2java
 */
class Examen : java.io.Serializable {
	var id: ExamenId? = null
	var alumne: Alumne? = null
	var qualificacio: Float? = null

	constructor() {}
	constructor(id: ExamenId?, alumne: Alumne?) {
		this.id = id
		this.alumne = alumne
	}

	constructor(id: ExamenId?, alumne: Alumne?, qualificacio: Float?) {
		this.id = id
		this.alumne = alumne
		this.qualificacio = qualificacio
	}
}