package classes
// Generated 15 de nov. 2020, 14:40:02 by Hibernate Tools 5.2.12.Final
/**
 * Practiques generated by hbm2java
 */
class Practiques : java.io.Serializable {
	var id: PractiquesId? = null
	var alumne: Alumne? = null
	var vehicle: Vehicle? = null
	var km: Short? = null
	var `val`: Float? = null

	constructor() {}
	constructor(id: PractiquesId?, alumne: Alumne?) {
		this.id = id
		this.alumne = alumne
	}

	constructor(id: PractiquesId?, alumne: Alumne?, vehicle: Vehicle?, km: Short?, `val`: Float?) {
		this.id = id
		this.alumne = alumne
		this.vehicle = vehicle
		this.km = km
		this.`val` = `val`
	}
}