package dades
// Generated 13 de nov. 2020, 8:14:54 by Hibernate Tools 5.2.12.Final
/**
 * PuntId generated by hbm2java
 */
class PuntId : java.io.Serializable {
	var numR: Int = 0
	var numP: Int = 0

	constructor() {}
	constructor(numR: Int, numP: Int) {
		this.numR = numR
		this.numP = numP
	}

	fun equals(other: Object?): Boolean {
		val o = other as PuntId
		if ((this === o))
			return true
		if ((other == null))
			return false
		if (!(o is PuntId))
			return false
		val castOther = other as PuntId?
		return (this.numR == castOther!!.numR) && (this.numP == castOther!!.numP)
	}

	override fun hashCode(): Int {
		var result = 17
		result = 37 * result + this.numR
		result = 37 * result + this.numP
		return result
	}
}