package dades
// Generated 13 de nov. 2020, 8:14:54 by Hibernate Tools 5.2.12.Final
/**
 * Punt generated by hbm2java
 */
class Punt : java.io.Serializable {
	var id: PuntId? = null
	var ruta: Ruta? = null
	var nomP: String? = null
	var latitud: Float? = null
	var longitud: Float? = null

	constructor() {}
	constructor(id: PuntId?, ruta: Ruta?) {
		this.id = id
		this.ruta = ruta
	}

	constructor(id: PuntId?, ruta: Ruta?, nomP: String?, latitud: Float?, longitud: Float?) {
		this.id = id
		this.ruta = ruta
		this.nomP = nomP
		this.latitud = latitud
		this.longitud = longitud
	}
}