package classesFactura
// Generated 19 de febr. 2021, 12:15:29 by Hibernate Tools 5.2.12.Final
import java.util.HashSet

/**
 * Client generated by hbm2java
 */
class Client : java.io.Serializable {
	var codCli: Int = 0
	var poble: Poble? = null
	var nom: String? = null
	var adreca: String? = null
	var cp: Integer? = null
	var facturas: Set<Factura>? = HashSet<Factura>(0)

	constructor() {}
	constructor(codCli: Int) {
		this.codCli = codCli
	}

	constructor(codCli: Int, poble: Poble?, nom: String?, adreca: String?, cp: Integer?, facturas: Set<Factura>?) {
		this.codCli = codCli
		this.poble = poble
		this.nom = nom
		this.adreca = adreca
		this.cp = cp
		this.facturas = facturas
	}
}